<a href="https://colab.research.google.com/github/Nagaramcheedella/DataScience_Learning/blob/main/DataScience_Python_Basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
# Enter - Just goes to next line within code block
# Alt + Enter - Executes the current line and creates a New Line (New Code Block)
# Shift + Enter - Executes the current line and goes to next line (Next Code Block)
# Ctrl + Enter - Executes the Current line only

In [ ]:
# () - FUNCTIONS
# {} - DICTIONARIES OR SETS
# [] - LISTS OR EXTRACTING DATA

In [ ]:
a = 20
type(a) # type() is function to get data type of a passed argument/Variable

int

In [ ]:
b = 20.5
type(b)

float

In [ ]:
c = "ram" # use '' or ""
type(c)

str

In [ ]:
d = True
type(d)

bool

In [ ]:
# packages - have lof of methods/functions
# import a package with import keyword  

In [ ]:
import math #math package

In [ ]:
#package.<module>.method() - hierrachy of syntax

In [ ]:
math.sqrt(81)

9.0

In [ ]:
# we can add 2 or more strings using '+' . But all components should be strings only

In [ ]:
greeting = "Good Morning "
name = "All"

message = greeting + name
message

'Good Morning All'

In [ ]:
  # Loops : while, for 
  # if, elif conditions

In [ ]:
i = 0
while i <= 10:
  print(i)
  i=i+1

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# range includes 0 and ignores the number we gave

In [ ]:
nway = [5,6,9]
for x in nway:
  print(x)

5
6
9


In [ ]:
# DATA STRUCTURES IN PYTHON

# LISTS, TUPLES, SETS, DATA FRAMES, DICTIONARIES, ARRAYS, MATRICES

In [ ]:
# List - []
# List is denoted with []
# We can list with mixed data types
# There can be a list in list
# lists are mutable

mylist = [1,2,3,]
mymixedlist = [1, "Ram", "Seetha", 12.9]

print(mylist, mymixedlist)

[1, 2, 3] [1, 'Ram', 'Seetha', 12.9]


In [ ]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [ ]:
# we can fetch values using index
list1[2]

3

In [ ]:
list1[-1] # when we use index as -1, it meand it is accessing from last

5

In [ ]:
# we can overwrite any element using index
list1[2] = "hello"
list1

[1, 2, 'hello', 4, 5]

In [ ]:
# We can perform slicing in list to fetch data
# slicing: Will fetch data in a list between provided range
# [x:y] will fetch from index 'x' to index 'y-1'

list2 = list(range(20))
list2


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
list2[2::6]

[2, 8, 14]

In [ ]:
list2[2:4] # will fetch data in range starting at 2nd index ends at (4-1)th index

[2, 3]

In [ ]:
list2[2:12]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
list3 = ['A','B','C','D','E','F','G','H','I','J']
list3

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [ ]:
list3[1:8:2] # slice will happen with step 2. Which is Alternate index

['B', 'D', 'F', 'H']

In [ ]:
list3[-9:-1:2]

['B', 'D', 'F', 'H']

In [ ]:
list3[1::2] # it will fetch from index 1 to end of list with step value/Interval value of 2

['B', 'D', 'F', 'H', 'J']

In [ ]:
list3[::3] # Will start from 0th index to end of list with stepvalue as 3

['A', 'D', 'G', 'J']

In [ ]:
list3[:7] # Will fetch from index 0 to index (7-1)

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [ ]:
list3[7:] # fetches from 7th index to end of list

['H', 'I', 'J']

In [ ]:
# we can reverse list using Negative Indexing
# -1 interval indicates reversing the list
list3[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [ ]:
list3[6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [ ]:
list3

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [ ]:
# Tuple: it is a immutable sequence of values
# We use () to indicate tuple
# we can give multiple data types in a tuple
# we can access any element in a tuple using []. Ex: tuple1(2) - which will fetch 2nd indexed element.

tuple1 = (1,"Ram", 10.2)
tuple1


(1, 'Ram', 10.2)

In [ ]:
# Since it is a immutable, we cant modify the tuple once it is created

tuple1(2) = 'seetha'

SyntaxError: ignored

In [ ]:
tuple1(2) = 23

SyntaxError: ignored

In [ ]:
tuple1[2] = 24

TypeError: ignored

In [ ]:
tuple1[2]

10.2

In [ ]:
tuple2 = tuple(range(1,20))
tuple2

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)

In [ ]:
# Arrays:
# we can slice arrays like lists

import numpy as np

listforarray = [1,2,3,4,5]
updated = np.array(listforarray)
updated

array([1, 2, 3, 4, 5])

In [ ]:
type(updated)

numpy.ndarray

In [ ]:
# If we have multiple data types in a list and we typecast it into array, it will convert all elements in list as strings
listforarray2 = [1,2,3,"ram", 10.4]
updatedmixed = np.array(listforarray2)
updatedmixed

In [ ]:
# We can update/modify an array using index
updatedmixed[2] = "hello"

In [ ]:
updatedmixed


array(['1', '2', '3', 'ram', '10.4'], dtype='<U32')

In [ ]:
# Although we update any integer element in a string array, it will store it as a string
updatedmixed[2] = 12

In [ ]:
updatedmixed

array(['1', '2', '12', 'ram', '10.4'], dtype='<U32')

In [ ]:
updated

array([1, 2, 3, 4, 5])

In [ ]:
# If we try to modify a Integer array with a string containing only numerics, then it willl store as integer value
updated[2] = "12"
updated

array([ 1,  2, 12,  4,  5])

In [ ]:
# if we try to modify a Integer Array with a string having "Alphanumerics", it will throw error
updated[2] = "Ram"


ValueError: ignored

In [ ]:
updated[2] = "hell22"

ValueError: ignored

In [ ]:
# range() - Useful in generating sequencing of numbers
# args: start,end and interval(optional)
# range(1,7) - 1,2,3,4,5,6
# range(1,10,2) - 1,3,5,7,9

list(range(1,7))

[1, 2, 3, 4, 5, 6]

In [ ]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [ ]:
# Functions are embedded in MOdules in Python
# USe 'import' keyword for importing Modules/Functions

In [ ]:
# Example:

import math


math.sqrt(64)

8.0